config/routes.rb
Rails.application.routes.draw do

  resources :skills
  resources :topics do
    resources :skills
    resources :supports
  end
  resources :users
  resources :supports do
    resources :comments, only: :create
    member do
      post :finish
      post :skip
      post :ack
    end
  end

  root :to => 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :support, counter_cache: true
  belongs_to :user

  scope :sorted, -> { order('created_at ASC') }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :topic, counter_cache: true

end

app/models/support.rb
class Support < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :receiver, class_name: 'User'
  belongs_to :user
  belongs_to :topic, counter_cache: true

  default_scope -> { order(updated_at: :desc) }
  scope :done, -> { where(done: true) }
  scope :not_done, -> { where(done: false) }
  scope :from_beginning_of_week, -> do
    done.where('supports.updated_at >= ?', Time.current.beginning_of_week)
  end

  def discussed?
    comments_count > 0
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  has_many :users, through: :skills
  has_many :skills

  default_scope -> { order('lower(title)') }
  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 6 }

  def to_s
    title
  end

  def users_count
    skills_count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :skills
  has_many :topics, through: :skills
  has_many :supports
  has_many :received_supports, as: :receiver
  has_many :comments

  default_scope { active }
  scope :active, -> { where(archived_at: nil) }
  scope :sorted, -> { order('supports_count DESC, lower(first_name) ASC') }

  def name
    "#{first_name} #{last_name}".strip
  end

  def to_s
    name
  end

  def has_pending_supports?
    supports.not_done.any?
  end

  def pending_supports_count
    supports.not_done.count
  end

  def helps_with?(topic)
    skills.where(topic_id: topic.id).any?
  end

  def archived?
    archived_at.present?
  end

  def self.this_week_best_users
    joins(:supports)
      .merge(Support.unscoped.from_beginning_of_week)
      .group('users.id')
      .order('COUNT(supports) DESC, lower(first_name) ASC')
      .limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  expose(:flash_alerts) { FlashDecorator.decorate_collection filtered_flash }
  protect_from_forgery with: :exception

  include StaticRoutes
  before_filter :login_required
  helper_method :logged_in?, :current_user

  private

  def login_required
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user ||= begin
      if session[:user_id] && (user = User.find_by(id: session[:user_id]))
        UserDecorator.decorate(user)
      end
    end
  end

  def filtered_flash
    flash.select{ |f| f[1].is_a?(String) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  expose_decorated(:support)

  def create
    comment = CommentOnSupport.new(current_user.object, support, comment_params)

    redirect_to support_path(support), notice: "You contributed to this support request"
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  expose(:recent_supports){
    SupportDecorator.decorate_collection Support.limit(20).done.includes(:user, :receiver, :topic)
  }
  expose(:waiting_for_help){
    SupportDecorator.decorate_collection Support.limit(20).not_done.includes(:user, :receiver, :topic)
  }

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :login_required

  expose(:failure_reason) { params[:message].presence || 'unknown' }

  def create
    login.commence!
    redirect_to root_path
  end

  def failure
  end

  private

  def auth_info
    request.env['omniauth.auth'].to_hash
  end

  def user_params
    raw_params = ActionController::Parameters.new(auth_info['info'])
    raw_params.permit(:first_name, :last_name, :email)
  end

  def login
    LogUserIn.new(session, user_params)
  end

  def failure_message
    params[:message].presence || 'unknown'
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  expose_decorated(:topics) { Topic.all }
  expose_decorated(:skills) { current_user.skills }
  expose_decorated(:topic) { Topic.find(params[:topic_id]) }


  def index
  end

  def create
    skill_registration = SkillRegistration.new(current_user.object, topic)
    skill_registration.commence!
    redirect_to skills_path
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController

  expose_decorated(:topic)    { Topic.find(params[:topic_id]) }
  expose_decorated(:support)  { Support.find(params[:id]) }
  expose_decorated(:comments) { support.comments.sorted }
  expose(:search_form) { SupportSearchForm.new Support.new, params[:support_search] }
  expose(:search) { SupportSearch.new params[:support_search] }
  expose_decorated(:supports, decorator: SupportCollectionDecorator) do
    search.paginated_results params[:page]
  end

  def index
  end

  def create
    need_support = AskForSupport.new(current_user.object, topic, support_params)
    need_support.commence!

    redirect_to root_path, notice: t('support.create.notice',
                                     name: need_support.supporter)
  end

  def skip
    skip_service = SkipSupport.new support
    skip_service.commence!
    if skip_service.success?
      redirect_to support_path(support), notice: t('support.skip.notice')
    else
      # FIXME: doesn't work with `error: ...` syntax (no flash wrapper)
      redirect_to support_path(support), flash: { error: t('support.skip.error') }
    end
  end

  def ack
    acknowledge_support = AcknowledgeSupport.new current_user.object, support
    acknowledge_support.commence!

    redirect_to support_path(support),
      notice: t('support.ack.notice')
  end

  def finish
    support_finish = FinishSupport.new(current_user.object, support)
    support_finish.commence!
    redirect_to root_path, notice: t('support.finish.notice')
  end

  private

  def support_params
    params.fetch(:support, {}).permit(:body, :user_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  expose(:support) { Support.new support_params }
  expose_decorated(:topics) { Topic.all }
  expose_decorated(:topic) { Topic.find(params[:id]) }
  expose_decorated(:random_supporter, decorator: UserDecorator) {
    topic.users.without(current_user.object).sample
  }

  before_filter :check_supporters_availability, only: :show

  def index
  end

  private

  def check_supporters_availability
    if random_supporter.nil?
      redirect_to topics_path, alert: t('topic.no_supporters')
    end
  end

  def support_params
    params.fetch(:support, {}).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose_decorated(:users) { User.sorted }
  expose_decorated(:this_week_best_users, decorator: UserDecorator) do
    User.this_week_best_users
  end
  expose_decorated(:user) { User.find params[:id] }
  expose_decorated(:supports) { user.supports.done }
  expose_decorated(:skills) { user.skills.includes(:topic) }
end

app/helpers/gravatar_helper.rb
module GravatarHelper

  def gravatar_image_tag email, size
    hash = Digest::MD5.hexdigest(email)
    image_tag "//www.gravatar.com/avatar/#{hash}?s=#{size}",
              height: size, width: size, class: 'user_avatar'
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.haml
.row
  .col-xs-12.event.comment{ id: dom_id(comment) }
    .image
      = comment.user.gravatar(37)
    .details
      .who
        %span.bold
          = comment.user
        wrote
      .when
        = comment.commented_at
      .comment-body.markdown-body= preserve comment.body

app/views/comments/_comments.html.haml
- if comments.any?
  = render comments

app/views/comments/_end.html.haml
.row
  .col-xs-12.event.done
    .image
      = image_tag('i/status-done.png')
    .details
      .who
        %span.bold
          = support.user
        marked as done
      .when
        = support.finished_at

app/views/comments/_form.html.haml
.row.new_comment_form_wrapper
  .pic-holder.hidden-xs.hidden-sm
    = current_user.gravatar(37)
  = simple_form_for :comment, url: support_comments_path(support), html: { id: 'new_comment_form', class: 'col-xs-12'} do |f|
    .markdown-panel
      .arrow.hidden-xs.hidden-sm
      .markdown-heading
        %ul
          %li.active= link_to '', '#write-content', data: { toggle: 'tab' }, id: 'write-tab', class: 'action-icon'
          %li= link_to '', '#preview-content', data: { toggle: 'tab' }, id: 'preview-tab', class: 'action-icon'

      .markdown-content
        #write-content.tab-pane.active
          = f.input :body, as: :text, label: false, input_html: { required: true },
            placeholder: 'Leave a comment'
        #preview-content.tab-pane.preview
    .action-panel
      = f.submit 'Comment', class: 'btn btn-success pull-right'

app/views/comments/_start.html.haml
.row
  .col-xs-12.event.start
    .image
      = image_tag('i/status-new.png')
    .details
      .who
        %span.bold
          = support.receiver
        asked for help
      .when
        = support.started_at

app/views/home/index.html.haml
%section.intro
  .container
    .row
      .col-xs-12
        %h3
          Have you been seen or been victim of social crime ask some one that can help!
        %h3
          We already solved
          %strong= Support.done.count
          requests but there are still
          %strong= Support.not_done.count
          requests to solve.

    .row
      .col-lg-4.col-lg-offset-4
        = link_to 'I need help', topics_path, class: 'btn btn--lg btn--block'

%section.requests
  .container
    .row
      .col-lg-6.col-lg-offset-3
        .box.supports-list
          %ul.nav.nav-tabs
            %li.box__tab.active= link_to 'Pending requests', '#pending_requests', data: { toggle: 'tab' }
            %li.box__tab= link_to 'Recently helped', '#recently_helped', data: { toggle: 'tab' }
          .tab-content
            .tab-pane.active#pending_requests
              %ul.supports
                - waiting_for_help.each do |support|
                  = render support
            .tab-pane#recently_helped
              %ul.supports
                - recent_supports.each do |support|
                  = render support

app/views/layouts/_back_to_home.html.haml
.col-xs-12.text-center.home_back
  = link_to root_path, class: 'btn btn-primary' do
    %i.glyphicon.glyphicon-fire
    Back to homepage

app/views/layouts/_messages.html.haml
.container
  .row
    - flash_alerts.each do |alert|
      .col-xs-12
        .alert{ class: alert.css_class }
          %button.close{ aria: { hidden: 'true' }, data: { dismiss: 'alert' }, type: 'button' } &times;
          %div{ id: alert.id }= alert.msg

app/views/layouts/_navigation.html.haml
%nav.navbar{ role: 'navigation' }
  .navbar-container
    .container
      .navbar-header
        = link_to 'Help App', root_path, class: 'navbar-brand'
        = link_to '#', class: 'navbar-toggle collapsed', data: { toggle: 'collapse', target: '.navbar-collapse' } do
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li= link_to 'Ranking', users_path
          %li= link_to 'Requests', supports_path
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'How can I help?', skills_path
          %li.navbar-avatar= link_to current_user.gravatar(36)

app/views/layouts/_navigation_links.html.haml
-# %li= link_to 'About', page_path('about')

app/views/layouts/_user_info.html.haml
.pull-right
  %h4
    #{current_user} - #{current_user.email}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Help'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Help'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    %main{ role: 'main', class: controller.controller_name }
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

app/views/skills/_skill.html.haml
= skill

app/views/skills/_topic.html.haml
.col-md-6
  = simple_form_for :skill, url: topic_skills_path(topic) do |f|
    = f.submit "#{topic} - #{current_user.help_summary(topic)}", class: "item #{current_user.topic_class(topic)}"

app/views/skills/index.html.haml
.container
  .row
    .col-xs-12
      %h2 Click on the topics you can help with:
  .row
    = render partial: 'topic', collection: topics
  = render 'layouts/back_to_home'

app/views/supports/_form.html.haml
.row
  .pic-holder.hidden-xs.hidden-sm
    = current_user.gravatar(60)

  = simple_form_for support, url: topic_supports_path(topic), html: { class: 'col-xs-12 padding-for-avatar' } do |f|
    = f.input :user_id, as: :hidden, input_html: { value: supporter.id }
    .markdown-panel
      .arrow.hidden-xs.hidden-sm
      .markdown-heading
        %ul
          %li.active= link_to '', '#write-content', data: { toggle: 'tab' }, id: 'write-tab', class: 'action-icon'
          %li= link_to '', '#preview-content', data: { toggle: 'tab' }, id: 'preview-tab', class: 'action-icon'

      .markdown-content
        #write-content.tab-pane.active
          = f.input :body, as: :text, label: false, input_html: { required: true },
            placeholder: 'Describe what do you need help with'
        #preview-content.tab-pane.preview

    .action-panel
      = link_to 'Select another supporter', '#', class: '', data: { another_supporter: true }
      = f.submit 'Ask for help', class: 'btn btn-primary'

app/views/supports/_list.html.haml
%td.request__column
  .image
    = support.state_image
%td.request__column
  = support.updated_at
%td.request__column
  = support.topic
%td.request__body
  = support.truncated_body
  = link_to "View problem (#{pluralize(support.comments_count, 'comment')})", support
%td.request__column
  = support.receiver_link
%td.request__column
  = support.user_link

app/views/supports/_support.html.haml
%li.support{ class: support.css_class }
  %p.support__folks= support.folks_label
  %p.support__category= support.topic
  %p.support__details
    = support.started_at
    = support.comments_label
  = link_to '', support

app/views/supports/index.html.haml
.container
  .row
    %h2
      All requests
      %span.filters-trigger.filters-hidden
        Show filters


    = simple_form_for search_form, url: request.url, method: :get, html: { class: 'form-horizontal' } do |f|
      .row
        .col-xs-8.col-sm-10
          = f.input :body, placeholder: 'What are you looking for?', label: false
        .col-xs-4.col-sm-2
          = f.submit 'Search', class: 'btn btn-primary search-button'
      .row.search-filters
        .col-xs-7.col-sm-4.col-md-3
          = f.input :state, collection: search_form.states, as: :radio_buttons, checked: search_form.state
        .col-xs-5.col-sm-3.col-md-3
          = f.input :topic_id, collection: search_form.topics
        .col-xs-6.col-sm-3.col-md-3
          = f.input :receiver_id, collection: search_form.users
        .col-xs-6.col-sm-2.col-md-3
          = f.input :user_id, collection: search_form.users

    %table.request
      %thead
        %tr.request__header.request__list
          %th.request__column State
          %th.request__column Updated
          %th.request__column Topic
          %th.request__body Problem
          %th.request__column Asked by
          %th.request__column Assigned to
      %tbody
        - supports.each_with_index do |support, i|
          %tr.request__list
            = render 'list', support: support, index: i
  .row
    .request
      %p= page_entries_info supports
      %p= will_paginate supports, container: false

app/views/supports/show.html.haml
.container
  .row
    .col-md-8
      .row
        .col-sm-8
          %h1.header-line
            = support.ticket_id
            %span.capitalize_text
              = support.topic
        .col-sm-4.supporter-panel
          = support.skip_button
          = support.action_button
      .row.hidden-xs
        .col-xs-12
          %h3.subheader-line
            = support.title
  .row
    .col-md-8
      .row
        .pic-holder.hidden-xs.hidden-sm
          = support.receiver.gravatar(60)
        .col-xs-12
          .row
            .col-xs-12.padding-for-avatar
              .markdown-panel
                .arrow.hidden-xs.hidden-sm
                %blockquote.markdown-body.request-preview= preserve support.body
          .row
            .col-xs-12.request-history.padding-for-avatar
              Request history
          .row
            .col-xs-12.comments.padding-for-avatar
              = render 'comments/start', locals: { support: support }
              = render 'comments/comments'
              - if support.done?
                = render 'comments/end', locals: { support: support }
              = render 'comments/form'

app/views/topics/_supporter.html.haml
%span.topic_supporter
  = link_to supporter, supporter, class: 'supporter_name'
  - if supporter.has_pending_supports?
    %span.supports_count
      = supporter.pending_supports_count

app/views/topics/_topic.html.haml
.col-md-6
  = link_to topic.show_link, class: 'item' do
    %span.item__count
      %span= topic.users_count
    %span.item__label= topic
    %span.item__description= topic.description

app/views/topics/index.html.haml
.container
  .row
    .col-xs-12
      %h2 Select the topic you need help with:
  .row
    = render partial: 'topic', collection: topics
  = render 'layouts/back_to_home'

app/views/topics/show.html.haml
.container
  .row
    .col-xs-12
      %h1.header-line
        Need help with
        %span.topic
          = "#{topic.small_title}?"
      %h5.header-line
        = topic.description
      %h3.subheader-line
        Fear not!
        %span.supporter_name
          = random_supporter
        is here to help!
  .row
    .col-md-8
      = render 'supports/form', supporter: random_supporter, topic: topic
    .col-md-2.hidden-xs.hidden-sm
      = random_supporter.gravatar(200)
  .row
    .col-md-8
      .supporters-panel
        We selected a random supporter for you. All people that signed for this topic are:
        .supporters-list
          = render partial: 'supporter', collection: topic.supporters

app/views/users/_user.html.haml
%li.position
  %span.position__index
    %span= '%02d' % index
  = user.gravatar(45)
  %span.position__name= user
  %span.position__score
    %span= supports_count
    pts
  = link_to '', user

app/views/users/index.html.haml
%section.ranking
  .container
    .row
      .col-lg-12
        %h2
          Best supporters!
    .row
      %h3
        This week:
    .row
      .col-lg-8
        %ol.leaderboard
          - this_week_best_users.each_with_index do |u, i|
            = render 'user', user: u, index: i + 1, supports_count: u.points_from_beginning_of_week
    .row
      %h3
        All the time:
    .row
      .col-lg-8
        %ol.leaderboard
          - users.each_with_index do |u, i|
            = render 'user', user: u, index: i + 1, supports_count: u.supports_count

app/views/users/show.html.haml
.container
  .row
    .col-md-6
      .user_header
        = user.gravatar(60)
        .user_info
          %h1.header-line
            = user
          %h3.subheader-line
            helped others
            %strong= user.supports_count
            times
          - if user.archived?
            %h4
              This user is
              %strong archived

      %ul.user_skills.box--rounded
        - skills.each do |skill|
          %strong.user_skill= render skill
    .col-md-6
      %ul.supports.box--rounded
        - supports.each do |support|
          = render support